name       : qgis
version    : 3.30.3
release    : 95
source     :
    - https://github.com/qgis/QGIS/archive/refs/tags/final-3_30_3.tar.gz : c8aa5d12d4c51849c61d6a8db8d3fb3cd2610ea50bea352658e9de603f1710de
homepage   : https://qgis.org/
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Free and Open Source Geographic Information System
description: |
    QGIS is a professional GIS application that is built on top of and proud to be itself Free and Open Source Software (FOSS). Create, edit, visualise, analyse and publish geospatial information on Windows, Mac, Linux, BSD (Android coming soon).
clang      : yes
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt53DExtras)
    - pkgconfig(exiv2)
    - pkgconfig(geos)
    - pkgconfig(gsl)
    - pkgconfig(harfbuzz)
    - pkgconfig(hdf5)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libssh)
    - pkgconfig(libzip)
    - pkgconfig(libzstd)
    - pkgconfig(netcdf)
    - pkgconfig(ocl-icd)
    - pkgconfig(pdal)
    - pkgconfig(proj)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(qca2-qt5)
    - pkgconfig(spatialite)
    - laz-perf-devel
    - libspatialindex-devel
    - pyqt-builder
    - python-qscintilla
    - python-sip
    - python-six
    - qscintilla-devel
    - qtkeychain-devel
    - qwt-devel
rundeps    :
    - geos
    - psycopg2
    - pygments
    - python-future
    - python-jinja
    - python-owslib
    - python-qscintilla
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/find-gsl-correctly.patch
    %patch -p1 < $pkgfiles/qgis_proj8.patch

    %cmake_ninja \
        -DENABLE_TESTS=FALSE \
        -DQGIS_MANUAL_SUBDIR=share/man \
        -DWITH_CUSTOM_WIDGETS=TRUE \
        -DWITH_PDAL=TRUE \
        -DWITH_3D=TRUE
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
