name       : qgis
version    : 3.8.2
release    : 50
source     :
    - https://github.com/qgis/QGIS/archive/final-3_8_2.tar.gz : 85be6520cf4dd35f2f5e6dd43f7fb56ff4ffa9bd00fca734433c31f0fe9e67bd
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Free and Open Source Geographic Information System
description: |
    QGIS is a professional GIS application that is built on top of and proud to be itself Free and Open Source Software (FOSS). Create, edit, visualise, analyse and publish geospatial information on Windows, Mac, Linux, BSD (Android coming soon).
builddeps  :
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5SerialPort)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt53DExtras)
    - pkgconfig(exiv2)
    - pkgconfig(gdal)
    - pkgconfig(gsl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libcurl)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libspatialindex)
    - pkgconfig(libssh)
    - pkgconfig(libzip)
    - pkgconfig(python3)
    - pkgconfig(qca2-qt5)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - geos
    - proj.4-devel
    - python-qscintilla
    - python-six
    - python3-qt5
    - python3-sip-devel
    - qscintilla-devel
    - qtkeychain-devel
    - qwt-devel
rundeps    :
    - geos
    - psycopg2
    - pygments
    - python3-qt5
    - python-future
    - python-jinja
    - python-owslib
    - python-qscintilla
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/fix-qt-5.13.patch

    %cmake_ninja -DENABLE_TESTS=FALSE -DWITH_3D=TRUE ..
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile
