name       : qgis
version    : 2.18.3
release    : 5
source     :
    - https://github.com/qgis/QGIS/archive/final-2_18_3.tar.gz : 3012afb6335564d95adf6798a97cc86a3a77787d88264e2943ee2419974b8ae2
license    : GPL-2.0
component  : desktop
summary    : QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)
description: |
    QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gsl)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libspatialindex)
    - pkgconfig(qca2)
    - pkgconfig(QJson)
    - pkgconfig(QtCore)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - geos
    - proj.4-devel
    - python-qscintilla
    - python-qt4
    - python-sip-devel
    - qscintilla-devel
    - qwt-devel
rundeps    :
    - psycopg2
    - python-jinja
    - pygments
    - python-qscintilla
    - python-qt4
setup      : |
    %patch -p1 < $pkgfiles/0002-fix-FindQCA.patch
    cp $pkgfiles/FindQsci.py cmake/
    %cmake -DENABLE_TESTS=0 -DWITH_QTWEBKIT=0 \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_QMAKE_EXECUTABLE=/usr/bin/qmake-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           -DWITH_BINDINGS=0 \
           .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/qgis.desktop $installdir/usr/share/applications/qgis.desktop
