name       : qgis
version    : 3.0.0
release    : 23
source     :
    - https://github.com/qgis/QGIS/archive/final-3_0_0.tar.gz : cb75bd4651f8491d93e75a0d1696320577ed36afc80a8f3b9a4dfb935aeccfc8
license    : GPL-2.0
component  : office.scientific
summary    : QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)
description: |
    QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libspatialindex)
    - pkgconfig(libzip)
    - pkgconfig(python-3.6)
    - pkgconfig(qca2-qt5)
    - pkgconfig(QJson)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - geos
    - proj.4-devel
    - python-qscintilla-qt5
    - python-six
    - python3-qt5
    - python3-sip-devel
    - qscintilla-qt5-devel
    - qtkeychain-devel
    - qwt-devel
rundeps    :
    - python-qscintilla-qt5
setup      : |
    #%patch -p1 < $pkgfiles/0002-fix-FindQCA.patch
    cp $pkgfiles/FindQsci.py cmake/
    %cmake -DENABLE_TESTS=FALSE .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/qgis.desktop $installdir/usr/share/applications/qgis.desktop
