name       : qgis
version    : 2.18.16
release    : 22
source     :
    - https://github.com/qgis/QGIS/archive/final-2_18_16.tar.gz : 7e224734fc1194025919c7e213379dffbd1d69d2807603bd88691be26649290c
license    : GPL-2.0
component  : office.scientific
summary    : QGIS is a free, open source, cross platform (lin/win/mac) geographical
    information system (GIS)
description: |
    QGIS is a free, open source, cross platform (lin/win/mac) geographical information system (GIS)
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gl)
    - pkgconfig(gsl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libspatialindex)
    - pkgconfig(qca2)
    - pkgconfig(QJson)
    - pkgconfig(QtCore)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - geos
    - proj.4-devel
    - python-qscintilla
    - python-qt4
    - python-sip-devel
    - qscintilla-devel
    - qwt-devel
rundeps    :
    - psycopg2
    - pygments
    - python-future
    - python-jinja
    - python-owslib
    - python-qscintilla
    - python-qt4
    - pyyaml
setup      : |
    %patch -p1 < $pkgfiles/0002-fix-FindQCA.patch
    cp $pkgfiles/FindQsci.py cmake/
    %cmake -DENABLE_TESTS=FALSE \
           -DWITH_QTWEBKIT=FALSE \
           -DWITH_INTERNAL_DATEUTIL=FALSE \
           -DWITH_INTERNAL_FUTURE=FALSE \
           -DWITH_INTERNAL_MARKUPSAFE=FALSE \
           -DWITH_INTERNAL_NOSE2=FALSE \
           -DWITH_INTERNAL_OWSLIB=FALSE \
           -DWITH_INTERNAL_PYTZ=FALSE \
           -DWITH_INTERNAL_SIX=FALSE \
           -DWITH_INTERNAL_YAML=FALSE \
           -DQT_MOC_EXECUTABLE=/usr/bin/moc-qt4 \
           -DQT_RCC_EXECUTABLE=/usr/bin/rcc-qt4 \
           -DQT_UIC_EXECUTABLE=/usr/bin/uic-qt4 \
           .
build      : |
    %make
install    : |
    %make_install
    install -D -m 00644 $pkgfiles/qgis.desktop $installdir/usr/share/applications/qgis.desktop
