name       : qgis
version    : 3.2.2
release    : 31
source     :
    - https://github.com/qgis/QGIS/archive/final-3_2_2.tar.gz : 0cc1f8daf2985a2dd88208d87b842c0667d6ec205abac1f002addbb11c8e6b98
license    : GPL-2.0-or-later
component  : office.scientific
summary    : A Free and Open Source Geographic Information System
description: |
    QGIS is a professional GIS application that is built on top of and proud to be itself Free and Open Source Software (FOSS). Create, edit, visualise, analyse and publish geospatial information on Windows, Mac, Linux, BSD (Android coming soon).
builddeps  :
    - pkgconfig(gdal)
    - pkgconfig(gsl)
    - pkgconfig(harfbuzz)
    - pkgconfig(icu-i18n)
    - pkgconfig(libpng)
    - pkgconfig(libpq)
    - pkgconfig(libspatialindex)
    - pkgconfig(libzip)
    - pkgconfig(python3)
    - pkgconfig(qca2-qt5)
    - pkgconfig(Qt5Positioning)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5UiTools)
    - pkgconfig(Qt5WebKit)
    - pkgconfig(Qt5XmlPatterns)
    - pkgconfig(spatialite)
    - pkgconfig(sqlite3)
    - geos
    - proj.4-devel
    - python-qscintilla-qt5
    - python-six
    - python3-qt5
    - python3-sip-devel
    - qscintilla-qt5-devel
    - qtkeychain-devel
    - qwt-devel
rundeps    :
    - geos
    - psycopg2
    - pygments
    - python3-qt5
    - python-future
    - python-jinja
    - python-owslib
    - python-qscintilla-qt5
    - pyyaml
setup      : |
    %cmake_ninja -DENABLE_TESTS=FALSE ..
build      : |
    %ninja_build
install    : |
    %ninja_install
    %python3_compile

    install -D -m 00644 $pkgfiles/qgis.desktop $installdir/usr/share/applications/qgis.desktop
